global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nas'
    static_configs:
      - targets: ['node-exporter:9100']

remote_write:
  - url: 'get_in_grafana_cloud_remote_write_endpoint'
    basic_auth:
      username: 'get_in_grafana_cloud_prometheus_details'
      password: 'get_in_grafana_cloud_api_keys'
